"use client"

import * as React from "react"
import { X, Link2, Copy, Check } from "lucide-react"

interface ShareModalProps {
    isOpen: boolean
    onClose: () => void
    noteTitle?: string
}

export function ShareModal({
    isOpen,
    onClose,
    noteTitle = "Untitled"
}: ShareModalProps) {
    const [collectPhone, setCollectPhone] = React.useState(false)
    const [collectName, setCollectName] = React.useState(false)
    const [canExportPDF, setCanExportPDF] = React.useState(true)
    const [anyoneWithLink, setAnyoneWithLink] = React.useState(true)
    const [copied, setCopied] = React.useState(false)

    // Generate a mock share link (in production, this would be generated by your backend)
    const shareLink = `https://notex.app/share/${noteTitle.toLowerCase().replace(/\s+/g, '-')}-${Math.random().toString(36).substr(2, 9)}`

    const handleCopyLink = async () => {
        try {
            await navigator.clipboard.writeText(shareLink)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        } catch (err) {
            console.error('Failed to copy:', err)
        }
    }

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === "Escape") {
            onClose()
        }
    }

    if (!isOpen) return null

    return (
        <div className="fixed top-4 right-4 z-50">
            <div
                className="bg-[var(--vscode-bg)] border border-[var(--vscode-border)] rounded-lg shadow-2xl w-[400px] overflow-hidden"
                onKeyDown={handleKeyDown}
                tabIndex={-1}
            >
                {/* Header */}
                <div className="px-4 py-3 border-b border-[var(--vscode-border)] flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <Link2 size={16} className="text-green-500" />
                        <h3 className="text-sm font-medium text-[var(--foreground)]">Share Note</h3>
                    </div>
                    <button
                        onClick={onClose}
                        className="text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors"
                    >
                        <X size={16} />
                    </button>
                </div>

                {/* Content */}
                <div className="p-4 space-y-4">
                    {/* Toggles Section */}
                    <div className="space-y-3">
                        <div className="flex items-center justify-between">
                            <label className="text-sm text-[var(--foreground)] cursor-pointer" htmlFor="collect-phone">
                                Collect phone
                            </label>
                            <button
                                id="collect-phone"
                                role="switch"
                                aria-checked={collectPhone}
                                onClick={() => setCollectPhone(!collectPhone)}
                                className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${collectPhone ? 'bg-green-600' : 'bg-[var(--vscode-sidebar-bg)]'
                                    }`}
                            >
                                <span
                                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${collectPhone ? 'translate-x-[18px]' : 'translate-x-[2px]'
                                        }`}
                                />
                            </button>
                        </div>

                        <div className="flex items-center justify-between">
                            <label className="text-sm text-[var(--foreground)] cursor-pointer" htmlFor="collect-name">
                                Collect name
                            </label>
                            <button
                                id="collect-name"
                                role="switch"
                                aria-checked={collectName}
                                onClick={() => setCollectName(!collectName)}
                                className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${collectName ? 'bg-green-600' : 'bg-[var(--vscode-sidebar-bg)]'
                                    }`}
                            >
                                <span
                                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${collectName ? 'translate-x-[18px]' : 'translate-x-[2px]'
                                        }`}
                                />
                            </button>
                        </div>

                        <div className="flex items-center justify-between">
                            <label className="text-sm text-[var(--foreground)] cursor-pointer" htmlFor="export-pdf">
                                Viewer can export as PDF
                            </label>
                            <button
                                id="export-pdf"
                                role="switch"
                                aria-checked={canExportPDF}
                                onClick={() => setCanExportPDF(!canExportPDF)}
                                className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${canExportPDF ? 'bg-green-600' : 'bg-[var(--vscode-sidebar-bg)]'
                                    }`}
                            >
                                <span
                                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${canExportPDF ? 'translate-x-[18px]' : 'translate-x-[2px]'
                                        }`}
                                />
                            </button>
                        </div>

                        <div className="flex items-center justify-between">
                            <label className="text-sm text-[var(--foreground)] cursor-pointer" htmlFor="anyone-link">
                                Anyone with this link
                            </label>
                            <button
                                id="anyone-link"
                                role="switch"
                                aria-checked={anyoneWithLink}
                                onClick={() => setAnyoneWithLink(!anyoneWithLink)}
                                className={`relative inline-flex h-5 w-9 items-center rounded-full transition-colors ${anyoneWithLink ? 'bg-green-600' : 'bg-[var(--vscode-sidebar-bg)]'
                                    }`}
                            >
                                <span
                                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${anyoneWithLink ? 'translate-x-[18px]' : 'translate-x-[2px]'
                                        }`}
                                />
                            </button>
                        </div>
                    </div>

                    {/* Divider */}
                    <div className="border-t border-[var(--vscode-border)]" />

                    {/* Link Section */}
                    <div className="space-y-2">
                        <label className="text-xs text-[var(--muted-foreground)] uppercase tracking-wider">
                            Share Link
                        </label>
                        <div className="flex gap-2">
                            <div className="flex-1 px-3 py-2 bg-[var(--vscode-sidebar-bg)] border border-[var(--vscode-border)] rounded text-xs text-[var(--foreground)] truncate">
                                {shareLink}
                            </div>
                            <button
                                onClick={handleCopyLink}
                                className={`px-3 py-2 rounded transition-all ${copied
                                    ? 'bg-green-600 text-white'
                                    : 'bg-blue-600 hover:bg-blue-700 text-white'
                                    }`}
                            >
                                {copied ? (
                                    <Check size={16} />
                                ) : (
                                    <Copy size={16} />
                                )}
                            </button>
                        </div>
                        {copied && (
                            <p className="text-xs text-green-500">Link copied to clipboard!</p>
                        )}
                    </div>
                </div>

                {/* Footer */}
                <div className="px-4 py-3 border-t border-[var(--vscode-border)] flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-4 py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
                    >
                        Done
                    </button>
                </div>
            </div>
        </div>
    )
}
